"""initial migration

Revision ID: 4ffc3a63f8d3
Revises: 
Create Date: 2025-08-21 20:44:45.520547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffc3a63f8d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('equipamentos', sa.String(length=200), nullable=False),
    sa.Column('abertura', sa.Time(), nullable=False),
    sa.Column('fechamento', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('professor', sa.Integer(), nullable=False),
    sa.Column('admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('solicitacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('data_encerramento', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_lab', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lab'], ['labs.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacoes')
    op.drop_table('users')
    op.drop_table('labs')
    # ### end Alembic commands ###
