"""add coluna status em solicitacao

Revision ID: 829be4d3284d
Revises: 4ffc3a63f8d3
Create Date: 2025-08-26 12:43:19.161117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829be4d3284d'
down_revision = '4ffc3a63f8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
